[package]
name = "rango-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
console = "0.15.8"
rango-sdk = "0.0.1"
tokio = { version = "1.36.0", features = ["full"] }
